<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta description="Our forte is building software applications for web and mobile platforms. The way we develop software applications, coding in particular, matters most. It's our responsibility to be creative and to be innovative in delivering software that harness the competitive advantage of our clients but most importantly we do it right.">
        <?php echo $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');
        ?>
        <?php echo $this->headTitle('Coding Matters')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        ?>
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/assets/font-awesome/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/assets/bootstrap/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/assets/bootstrap/css/bootstrap.min.css')
        ?>
    </head>
    <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
        <!-- Navigation -->
        <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand page-scroll" href="<?php echo $this->url('home'); ?>">
                        <img src="<?php echo $this->basePath(). "/img/logo-inline.png";?>" class="logo" alt="Coding Matters Logo" data-src="<?php echo $this->basePath(). "/img/logo-inline.png";?>" data-src-retina="<?php echo $this->basePath(). "/img/logo-inline.png";?>" width="250px"/>
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                    <ul class="nav navbar-nav">
                        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                        <li class="hidden">
                            <a href="#page-top"></a>
                        </li>
                        <li>
                            <a class="page-scroll" href="#services">SERVICES</a>
                        </li>
                        <li>
                            <a class="page-scroll" href="#about">ABOUT</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <!-- Intro Header -->
<!--        <header class="intro">
            <div class="intro-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <h1 class="brand-heading">Why <strong>CODING MATTERS&#63</strong></h1>
                            <p class="intro-text">We are creative and innovative for business processes that harness the competitive advantage of our clients. Most importantly, the way we develop software applications, coding in particular, matters most. <strong>WE DO IT RIGHT</strong>.</p>
                        </div>
                    </div>
                </div>
            </div>
        </header>-->
        <!--<div class="container">-->
        <?php echo $this->content; ?>
        <!--</div>-->
        <footer>
            <?php echo $this->partial('template/footer', array()); ?>
        </footer>
        
        <?php $this->inlineScript()
            ->prependFile($this->basePath() . '/js/navbar-header-collapse.js')
            ->prependFile($this->basePath() . '/assets/bootstrap/js/tab.js')
            ->prependFile($this->basePath() . '/assets/bootstrap/js/tooltip.js')
            ->prependFile($this->basePath() . '/assets/bootstrap/js/popover.js')
            ->prependFile($this->basePath() . '/assets/jquery-ui/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/assets/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/jquery/jquery.min.js');
        ?>
        
        <?php
            /**
             * USED FOR SITE ANALYTICS. DO NOT EDIT BEYOND THIS LINE.
             */
            if (strtolower($_SERVER['APPLICATION_ENV'])  === 'production') {                
        ?>
            <!-- Google Tag Manager -->
            <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-TXBXSJ"
            height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
            <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-TXBXSJ');</script>
            <!-- End Google Tag Manager -->
        <?php
            }
        ?>
        
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
