<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">        
        <?php echo $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');
        ?>
        <?php echo $this->headTitle('Coding Matters, Inc.')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        ?>
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath() . '/assets/font-awesome/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/assets/bootstrap/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/assets/bootstrap/css/bootstrap.min.css')
        ?>
    </head>
    <body>
        <header>
             
        </header>
        <section>
            <div class="mainwrapper">
                <?php echo $this->content; ?>
            </div>
        </section>
        <footer>
            
        </footer>
        <?php echo $this->inlineScript()           
            ->prependFile($this->basePath() . '/assets/bootstrap/js/tab.js')
            ->prependFile($this->basePath() . '/assets/bootstrap/js/tooltip.js')
            ->prependFile($this->basePath() . '/assets/bootstrap/js/popover.js')
            ->prependFile($this->basePath() . '/assets/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/jquery/jquery.min.js');
        ?>
    </body>
</html>
