<div class="headerwrapper">
    <div class="header-left">
        <a href="<?php echo $this->url('home'); ?>"><img src="<?php echo $this->basePath(). "/assets/img/logo.png";?>" class="logo" alt=""  data-src="<?php echo $this->basePath(). "/assets/img/logo.png";?>" data-src-retina="<?php echo $this->basePath(). "/assets/img/logo.png";?>" width="92" height="20"/></a>
        <div class="pull-right">
            <a href="#" class="menu-collapse">
                <i class="fa fa-bars"></i>
            </a>
        </div>
    </div>
    <div class="header-right">
         <div class="pull-left">
            <?php
//                echo $this->navigation("header")->menu()->setPartial("template/navigation/header");
            ?>
        </div>
        <div class="pull-right">
            <div class="btn-group btn-group-option">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-lock"></i>
                </button>               
                <ul class="dropdown-menu pull-right" role="menu">
                  <li><a href="<?php // echo $this->url("zfcuser/logout"); ?>"><i class="glyphicon glyphicon-log-out"></i>Sign Out</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>