<div class="media profile-left">
    <a class="pull-left profile-thumb" href="<?php echo $this->url('home');?>">
        <img class="img-circle" src="<?php echo $this->basePath(). "/assets/webarch/img/profiles/avatar.jpg";?>" >
    </a>
    <div class="media-body">
        <h4 class="media-heading">&nbsp;&nbsp;Nickname</h4>
        <small class="text-muted">&nbsp;&nbsp;Executive Assistant</small>
    </div>
</div>
<h5 class="leftpanel-title">Navigation</h5>
<?php 
    echo $this->navigation("sidebar")->menu()->setPartial("template/navigation/sidebar");
?>