<section id="services">
    <div class="container">
        <div class="row text-center">
            <h1 class="text-uppercase"><strong>we can help you</strong></h1>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <h1>BUILD</h1>
                <div>
                    <p class="text-justify">We help to build your business through our creative and innovative minds. Turning your ideas into a software. (Let’s MAKE it happen)</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4">
                <h1>REVAMP</h1>
                <div>
                    <p class="text-justify">Having trouble with you current manual process? (Let’s AUTOMATE) 
    </p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4">
                <h1>PROVIDE</h1>
                <div>
                    <p class="text-justify">You need a service to scale your process? (Let’s HOST them)</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="about" class="container">
    <div class="container">
        <div class="row">
            <h3><strong>About Us</strong></h3>
            <p class="text-justify">
                <strong><q>Coding Matters, Inc.</q></strong> is formed because of one common goal. To help and to reach out to business organizations in order to provide solutions that harness their business process as their competitive advantage in the market.
            </p>
            <p class="text-justify">
                We follow specific core values of principles and disciplines as our credo in order for us to develop high quality, extendable and scalable software applications.
            </p>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <p class="text-success"><strong class="text-uppercase">Mission</strong></p>
                <ul>
                    <li>
                        To be able to help business organizations in providing solutions that harness their business process as their competitive advantage over the market.
                    </li>
                </ul>
            </div>
            <div class="col-md-6 col-sm-6">
                <p class="text-success"><strong class="text-uppercase">Vision</strong></p>
                <ul>
                    <li>
                        Globally known IT solutions company renowned for its excellence in computational thinking and its commitment to software applications research and development.
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>


