<section id="services">
    <div class="container">
        <div class="row text-center">
            <h1 class="text-uppercase"><strong>we can help you</strong></h1>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <h1>BUILD</h1>
                <div>
                    <p class="text-justify">We help to build your business through our creative and innovative minds. Turning your ideas into a software. (Let’s MAKE it happen)</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4">
                <h1>REVAMP</h1>
                <div>
                    <p class="text-justify">Having trouble with you current manual process? (Let’s AUTOMATE) 
    </p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4">
                <h1>PROVIDE</h1>
                <div>
                    <p class="text-justify">You need a service to scale your process? (Let’s HOST them)</p>
                </div>
            </div>
        </div>
    </div>
</section>